2022-12-19 20:32:55,850 INFO    MainThread:47193 [wandb_setup.py:_flush():68] Configure stats pid to 47193
2022-12-19 20:32:55,850 INFO    MainThread:47193 [wandb_setup.py:_flush():68] Loading settings from /Users/estellaxin/.config/wandb/settings
2022-12-19 20:32:55,850 INFO    MainThread:47193 [wandb_setup.py:_flush():68] Loading settings from /private/var/folders/vh/k98fyx251l792bbzj485tdnw0000gp/T/tmpskcg3byk/wandb/settings
2022-12-19 20:32:55,850 WARNING MainThread:47193 [wandb_setup.py:_flush():68] Unknown environment variable: WANDB_REQUIRE_REPORT_EDITING_V0
2022-12-19 20:32:55,850 WARNING MainThread:47193 [wandb_setup.py:_flush():68] Unknown environment variable: WANDB_ERROR_REPORTING
2022-12-19 20:32:55,850 INFO    MainThread:47193 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True', 'username': 'test_lazy_artifact_passthrough', 'base_url': 'http://localhost:65214', 'api_key': '***REDACTED***'}
2022-12-19 20:32:55,850 INFO    MainThread:47193 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-12-19 20:32:55,850 INFO    MainThread:47193 [wandb_init.py:_log_setup():476] Logging user logs to /Users/estellaxin/Projects/wandb/tests/unit_tests_old/logs/test_lazy_artifact_passthrough/wandb/run-20221219_203255-ghlqul1m/logs/debug.log
2022-12-19 20:32:55,851 INFO    MainThread:47193 [wandb_init.py:_log_setup():477] Logging internal logs to /Users/estellaxin/Projects/wandb/tests/unit_tests_old/logs/test_lazy_artifact_passthrough/wandb/run-20221219_203255-ghlqul1m/logs/debug-internal.log
2022-12-19 20:32:55,851 INFO    MainThread:47193 [wandb_init.py:init():516] calling init triggers
2022-12-19 20:32:55,851 INFO    MainThread:47193 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-12-19 20:32:55,851 INFO    MainThread:47193 [wandb_init.py:init():569] starting backend
2022-12-19 20:32:55,851 INFO    MainThread:47193 [wandb_init.py:init():573] setting up manager
2022-12-19 20:32:55,858 INFO    MainThread:47193 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-12-19 20:32:55,859 INFO    MainThread:47193 [wandb_init.py:init():580] backend started and connected
2022-12-19 20:32:55,866 INFO    MainThread:47193 [wandb_init.py:init():658] updated telemetry
2022-12-19 20:32:55,867 INFO    MainThread:47193 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-12-19 20:32:56,118 INFO    MainThread:47193 [wandb_run.py:_on_init():2000] communicating current version
2022-12-19 20:32:56,408 INFO    MainThread:47193 [wandb_run.py:_on_init():2004] got version response upgrade_message: "wandb version 0.13.7 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"
delete_message: "wandb version 0.13.5.dev1 has been retired!  Please upgrade."

2022-12-19 20:32:56,408 INFO    MainThread:47193 [wandb_init.py:init():728] starting run threads in backend
2022-12-19 20:32:56,620 INFO    MainThread:47193 [wandb_run.py:_console_start():1980] atexit reg
2022-12-19 20:32:56,621 INFO    MainThread:47193 [wandb_run.py:_redirect():1838] redirect: SettingsConsole.OFF
2022-12-19 20:32:56,622 INFO    MainThread:47193 [wandb_init.py:init():765] run started, returning control to user process
2022-12-19 20:33:00,429 ERROR   MainThread:47193 [retry.py:__call__():154] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/estellaxin/Projects/wandb/wandb/sdk/lib/retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/estellaxin/Projects/wandb/wandb/apis/public.py", line 240, in execute
    return self._client.execute(*args, **kwargs)
  File "/Users/estellaxin/Projects/wandb/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/estellaxin/Projects/wandb/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/estellaxin/Projects/wandb/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/Users/estellaxin/Projects/wandb/.tox/py38/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:65214/graphql
2022-12-19 20:33:30,637 INFO    MainThread:47193 [wandb_run.py:_finish():1746] finishing run mock_server_entity/test/ghlqul1m
2022-12-19 20:33:30,637 INFO    MainThread:47193 [wandb_run.py:_atexit_cleanup():1949] got exitcode: 0
2022-12-19 20:33:30,637 INFO    MainThread:47193 [wandb_run.py:_restore():1932] restore
2022-12-19 20:33:30,637 INFO    MainThread:47193 [wandb_run.py:_restore():1938] restore done
2022-12-19 20:33:37,565 INFO    MainThread:47193 [wandb_run.py:_footer_history_summary_info():3377] rendering history
2022-12-19 20:33:37,565 INFO    MainThread:47193 [wandb_run.py:_footer_history_summary_info():3409] rendering summary
2022-12-19 20:33:37,567 INFO    MainThread:47193 [wandb_run.py:_footer_sync_info():3333] logging synced files
